// <auto-generated />
using IS413_Mission06_jel14t.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IS413_Mission06_jel14t.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20230211030948_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("IS413_Mission06_jel14t.Models.MovieEntryModel", b =>
                {
                    b.Property<int>("EntryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("EntryID");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            EntryID = 1,
                            category = "Action/Adventure",
                            director = "John McTiernan",
                            edited = true,
                            rating = "R",
                            title = "Die Hard",
                            year = 1988
                        },
                        new
                        {
                            EntryID = 2,
                            category = "Action/Adventure",
                            director = "Roland Emmerich",
                            edited = false,
                            rating = "PG-13",
                            title = "Independence Day",
                            year = 1996
                        },
                        new
                        {
                            EntryID = 3,
                            category = "Comedy",
                            director = "John Hughes",
                            edited = true,
                            lentTo = "Dave",
                            notes = "What an interesting movie",
                            rating = "R",
                            title = "Planes, Trains and Automobiles",
                            year = 1987
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
