// <auto-generated />
using IS413_Mission06_jel14t.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IS413_Mission06_jel14t.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("IS413_Mission06_jel14t.Models.Category", b =>
                {
                    b.Property<int>("categoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("categoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("categoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            categoryID = 1,
                            categoryName = "Action/Adventure"
                        },
                        new
                        {
                            categoryID = 2,
                            categoryName = "Comedy"
                        },
                        new
                        {
                            categoryID = 3,
                            categoryName = "Drama"
                        },
                        new
                        {
                            categoryID = 4,
                            categoryName = "Family"
                        },
                        new
                        {
                            categoryID = 5,
                            categoryName = "Horror/Suspense"
                        },
                        new
                        {
                            categoryID = 6,
                            categoryName = "Miscellaneous"
                        },
                        new
                        {
                            categoryID = 7,
                            categoryName = "Television"
                        },
                        new
                        {
                            categoryID = 8,
                            categoryName = "VHS"
                        });
                });

            modelBuilder.Entity("IS413_Mission06_jel14t.Models.MovieEntryModel", b =>
                {
                    b.Property<int>("EntryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("categoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("EntryID");

                    b.HasIndex("categoryID");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            EntryID = 1,
                            categoryID = 1,
                            director = "John McTiernan",
                            edited = true,
                            rating = "R",
                            title = "Die Hard",
                            year = 1988
                        },
                        new
                        {
                            EntryID = 2,
                            categoryID = 1,
                            director = "Roland Emmerich",
                            edited = false,
                            rating = "PG-13",
                            title = "Independence Day",
                            year = 1996
                        },
                        new
                        {
                            EntryID = 3,
                            categoryID = 2,
                            director = "John Hughes",
                            edited = true,
                            lentTo = "Dave",
                            notes = "What an interesting movie",
                            rating = "R",
                            title = "Planes, Trains and Automobiles",
                            year = 1987
                        });
                });

            modelBuilder.Entity("IS413_Mission06_jel14t.Models.MovieEntryModel", b =>
                {
                    b.HasOne("IS413_Mission06_jel14t.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("categoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
